package:
  name: llvmmath
  version: 99.9.9

source:
  git_url: git@github.com:ContinuumIO/llvmmath.git
  #git_tag: 0.1.1

requirements:
  build:
    - python
    - llvmpy
    - numpy
    #- chrpath       [linux]
  run:
    - python
    - llvmpy
    - numpy

test:
  requires:
    - nose
  imports:
    - llvmmath
